from itertools import tee, izip, islice
s="MEIGWDDNTLMQMSTPMNDIMFEPIHFLCWAYQWLNPNLVALTPFKVRVKILKHPKFGWCYQCQLANEGGNADKVFVLDKGAVKLGTDQYMIADAMRLIASRHHNYMAMGYMEWANCHDYIGWTQFKCMRTLTRPLLEFKMHIWKPDAMCKQDEPPIDYAGSVNTQKWCQRFKPKKTKCTATPHRCSEEQVCQQSRITLREADGRDKCYIPWWNDMAQLTPKGCLCKFLEHAADARRCKWPKCSFADFKADLHHGGTLRDRDLVHAFAVMCNQTGILNMKPACYSPAYPPDYYLMCGNSPRASLDQTFVYLFLCFQASTDIWKYPEWMAQCCDEHDRAKWIYFYGHDNSSVHNNKLPPAWYVFWFYKPEVDQEHQDQCDHHHNGEMARIETPMMITVSFNVPWVQGSIIRNQPNMHTQDPPHLRPLDSIRDKIWMQERYDVDWDHWPIGQKFGNEHKNFIDHGVTMYPEQTHTIHADTAFCACNSEYPYSMNLGLSKEHINWNYAEHRGRSEVDYNLKTMHMASPWDDRTVPMWMATIVTDDQLTTFQASSDGAKSCCECMVVVWFSHSYPIPLKTDIQQPKRAKEHQNWSEIKMNNNCVQLGHVRMMFTCHQMPDGCINDCGIMISRYTIIYGWPAPGPPTSTWQMFDRFKWWRILSIAKWRLMDMTRVGKVVFRIQPDKLMNSFGSLNQPKKNNCEWDQLVHHKNKTSVAPTVMGYGVTVYLFIGQYIMSVAKITIPHEDWTRPDWVWHPKHENKSMWSTPQRVYRHCCYCFNTGWSTIWNANNYHSHAKMEPWHWIWRGGGSRWFWVFEKLHASPIPYIWSYDVPCHTIEQCSRNWIHSVDRERVWATTFMQCDHHFSDIWSRWHGNFLWDKIMAFSLLVKWNCIKARHINKQSEHCLRHNMRFCEKHGWVPMHRCVTNPNIHWTLRPIHKPMHWGKMIEHMYEPYLFWSSGPMTYAGADHEDSWHTRYAGKACVFVFFGFSNVTLPTYCIWPKMTC"
t=tee(s, 1)
for i, j in enumerate (t):
	next(islice(j, i, i), None)
p=["".join(k) for k in izip(*t)]
print p
z=3
for i in p:
	if i=="F":
		z*=2
	if i=="L":
		z*=6
	if i=="I":
		z*=3
	if i=="V":
		z*=4
	if i=="S":
		z*=6
	if i=="P":
		z*=4
	if i=="T":
		z*=4
	if i=="A":
		z*=4
	if i=="Y":
		z*=2
	if i=="H":
		z*=2
	if i=="Q":
		z*=2
	if i=="N":
		z*=2
	if i=="K":
		z*=2
	if i=="D":
		z*=2
	if i=="E":
		z*=2
	if i=="C":
		z*=2
	if i=="R":
		z*=6
	if i=="G":
		z*=4
print z % 1000000