#set d equal to the DNA string and remove it from the txt file
d="ATGGGCCCATATATTCTCAAAGAAAGGTGTGGAGCGCTTGCACAGTCCGATATTCCCTCGCTTCCCGAACCACACCTGTATCACCGGGATGAATACCATCAGGCCGCAGACCCTCGCCCCAGGAGGGGACGTTTTTCCGATGAGGACTGTCGGTGCGTACTCGCCCTCACGTACTGGTTGGTTGGTCGCAAAGTCAAGAGAACGTTCGAAGACATGGATTGTTGTGGAGTCATAGGCGCAATAGTAAACTCAAATGTATCGTAGGAATCATCTTCCTGCAAGGAATAACGTGGAGAGAGCAAGCCCCGTCTTTAGACGTCAAAGTAGGTTGCGCCAAAGAAAGTTTTTATCCATTTCTGACGTACCACCAGCTATACTGCAGGCGCCACGACGAATCGGCGTACTCTATCGAGACGGGGAGCTAATAGCCGTACTCAAAAATGGACGAGTTTTTCGTTCGATCAGGAGCTACGCAAAGGTTCGGAGGGATCTTGATCGGTATGATATTAAAGCGTGGATGCAGGAATCGTGGATCGGTACCTAACACAGGAACTCGGGACGTCAGTTTACTTTCTTAGGGTCGGGAGCTCTTTCTAGTAGGCACCCGACCCCGGACAAAGGCGCGTCGCCATCTCTAGTAGGCCGTCATACATACAATTAGTCCGCAATCAGTTATGTCGATTCGATTGTACGGGGACGTCTCCACTGTATACGAAACCTTCGATTTATGTTTAATACCGATAGAGCCAAGATCGGAAGATGTGGGTGCGAGTCGAGTCCGGAAGCAAAAAGGAGACCTAAACTTACGACGGTGTGCCGCATCTTAATGGGTGCACAGCACCTCTCAGCGCAACTACTCAAACGCAGTTTATCTTCCCACCTTGTAGTAGGTGAGTTACCCTTGGCAAGGTTACAGCTGGCAGCTAGAACTCATATTGCTGCGATCGCATCCGGGATTGTCCCGCGTGCATATGCAATCATGA"
import fileinput
import string
s=open("/Users/Mcfoofa/Downloads/rosalind_splc.txt", "r")
l = [ ]
for line in s:
	line=line.replace("\n", "")
	l.append(line)
p = { }
count = 0
for item in l:
	if item[0]==">":
		w=item[1:]
		p[w]=l[count+1]
		count+=1
	else:
		count+=1
k = [ ] 
s.close()
print p
for j in p:
	q=p[j]	
	if q in d:
		d=d.replace(q, "")
print d
def rna_protein(s):
	s2=[ s[start:start+3] for start in range(0, len(s), 3) ]
	m=" "
	g = {"ATT": "I", "ATC": "I", "ATA": "I", "CTT": "L", "CTC": "L", "CTA": "L", "CTG": "L", "TTA": "L", "TTG": "L", "GTT": "V", "GTC": "V", "GTA": "V", "GTG": "V", "TTT": "F", "TTC": "F", "ATG": "M", "TGT": "C", "TGC": "C", "GCT": "A", "GCC": "A", "GCA": "A", "GCG": "A", "GGT": "G", "GGC": "G", "GGA": "G", "GGG": "G", "CCT": "P", "CCC": "P", "CCA": "P", "CCG": "P", "ACT": "T", "ACC": "T", "ACA": "T", "ACG": "T", "TCT": "S", "TCC": "S", "TCA": "S", "TCG": "S", "AGT": "S", "AGC": "S", "TAT": "Y", "TAC": "Y", "TGG": "W", "CAA": "Q", "CAG": "Q", "AAT": "N", "AAC": "N", "CAT": "H", "CAC": "H", "GAA": "E", "GAG": "E", "GAT": "D", "GAC": "D", "AAA": "K", "AAG": "K", "CGT": "R", "CGC": "R", "CGA": "R", "CGG": "R", "AGA": "R", "AGG": "R"}
	for r in s2:
		if r in g:
			m+=g[r]
	print m
rna_protein(d)